# Release.toml
sign-commit = false
sign-tag = false
push = true
publish = true
tag-name = "v{{version}}"
pre-release-commit-message = "chore: release {{version}}"
release-commit-message = "chore: release {{version}}"
tag-message = "Release {{version}}"
