name: Dependency Check

on:
  push:
  pull_request:

jobs:
  udeps:
    name: Check for Unused Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo-udeps
        run: cargo install cargo-udeps

      - name: Run cargo udeps
        run: cargo udeps --all-targets --all-features
